project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Squirrels in Central Park"
  author:
    - Jiayi Dong (jd4123)
    - Zimeng(Sandy) Li (zl2804)
  repo-url: https://github.com/JiayiD8/squirrels_in_central_park
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


