# Interactive graph

<style>
  * {
    font-family: sans-serif;
  }
</style> 

<div id="plot">
</div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="https://d3js.org/d3-hexbin.v0.2.min.js"></script>
<script src="scripts/myscript.js"></script>

```{r}
# Get the data for interactive graph
# library(tidyverse)
# library(jsonlite)
# 
# squirrel_data <- read.csv("data/2018_Central_Park_Squirrel_Census_-_Squirrel_Data_20241120.csv")
# 
# squirrel_coords <- squirrel_data |>
#   mutate(across(Primary.Fur.Color, ~ na_if(as.character(.), ""))) |>
#   drop_na(Primary.Fur.Color) |>
#   select(X, Y, Primary.Fur.Color) |>
#   rename(longitude = X,
#          latitude = Y,
#          furColor = Primary.Fur.Color)
# 
# # Export the data as JSON
# write_json(squirrel_coords, "squirrel_coords.json")
```

## How to interact with the graph?
This graph explores squirrel sightings across Central Park. The darker blue hexagon indicates a higher concentration of squirrel sightings in that area. The hexagons are plotted with their actual spacial locations, resulting in a overall shape resembles Central Park. 

**Hover your cursor over the hexagons**\
To explore detailed squirrel sighting information, move your cursor over any blue hexagon on the map. A small window will appear showing both the total number of squirrels spotted in that specific area and a breakdown of counts for each fur color.

**Pick the fur color you are interested in**\
Use the checkboxes below the graph to select which fur colors you want to display on the map. You can choose to view any combination of gray, cinnamon, and black squirrels. You can also use the "Select All" button to show all fur colors at once, or "Clear All" deselect everything.

## Did you spot any interesting patterns?
Standard gray squirrels were sighted across the Central Park, as this is the most common fur color. But there are still several significant clustering of sightings located at south west corner of the park, middle of the park and north of the Jacqueline Kennedy Onassis Reservoir. Cinnamon squirrels sightings were clustered at the south west corner of the park as well, while spreading sporadically across north of the park. Black squirrels were encountered the fewest, mostly at the north of the park.

Interestingly, both gray and cinnamon squirrels were sighted a lot at the south west corner of the park, near the Columbus Circle. The popularity of this entrance may lead people to feed the squirrels more frequently or leave more food debris behind. Thus more squirrels are attracted to here.

The distribution of cinnamon and black squirrels sightings locations have only a few overlapping areas. This is an intriguing pattern we noticed but we also don't have a proper explanation.