# Data

## Description

The 2018 Central Park Squirrel Census dataset is a squirrel sighting data collected by 23 volunteer Squirrel Sighters in October of 2018. Throughout two weeks of time, they will walk around the Central Park and document each sighting of squirrels. From their website The Squirrel Census, they don't have a specific data collecting and updating cycle, as they collected data in 2012, 2016, 2018 and 2020. This may due to the fact that this is more like a volunteering project. We are not using the latest data because it only includes 434 sightings but were collected from 24 different parks, making the data too sparse to analyze. Therefore, we choose the 2018 dataset that focused on the squirrels in Central Park. The dataset is in tabular format with 3023 rows and 31 columns. Each row is an instance of sighting squirrels. The columns capture different aspect of the sighting, including location, time, number of squirrels, what were squirrels doing, etc. The data were well-collected and well-documented, so there is no issue interpreting them. One issue was some data are in the type of Checkbox, but if downloading the dataset as a csv file, which is an available option, Checkbox type will be automaticly convert into True and False values. Additionally, there are some extra information columns that contains field notes, which we need to consider how to deal with. 

## Missing value analysis
